services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: feichai@123456
      POSTGRES_DB: yun_ai_server_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: ['CMD','pg_isready']
      interval: 1s
      timeout: 3s
      retries: 30
  redis:
    image: redis:6.0
    container_name: yun_ai_server_redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis-data:/data
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5