app:
  version: v1.0.1
  name: yun-ai-server
  idle_time_out: 5
  read_time_out: 5
  write_time_out: 5
  port: 8099
  env: debug
  desc: AI应用
logger:
  logFilePath: .logs/
  logFileName: app.log
  # Go 中的时间格式化使用特定的参考时间作为模板
  logTimestampFmt: '2006-01-02 15:04:05'
  # 文件的最大保存时间: 我们日志文件最大保留 3 天 (3 * 24 H)
  logMaxAge: 72
  # 日志轮转频率: 每 24 小时轮转一次
  logRotationTime: 24
  logLevel: INFO
db:
  name: yun_ai_server_db
  host: 127.0.0.1
  port: 5432
  user: postgres
  psw: yinglian@123456
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  pws: